// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Shared_Static_Class.Data;

namespace Shared_Static_Class.DB_Context_Vivo_MAIS
{
    public partial class Vivo_PBIContext : DbContext
    {
        public Vivo_PBIContext()
        {
        }

        public Vivo_PBIContext(DbContextOptions<Vivo_PBIContext> options)
            : base(options)
        {
        }

        public virtual DbSet<fGOESTOQUE> fGOESTOQUEs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("connectionstring"
                    , o => o.UseCompatibilityLevel(120));
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fGOESTOQUE>(entity =>
            {

                entity.ToTable("fGOESTOQUE");

                entity.Property(e => e.Cor).HasMaxLength(255);

                entity.Property(e => e.Data).HasColumnType("datetime");

                entity.Property(e => e.Data_Compra)
                    .HasColumnType("datetime")
                    .HasColumnName("Data Compra");

                entity.Property(e => e.Dias_em_Estoque)
                    .HasMaxLength(255)
                    .HasColumnName("Dias em Estoque");

                entity.Property(e => e.Filial_Estoque)
                    .HasMaxLength(255)
                    .HasColumnName("Filial Estoque");

                entity.Property(e => e.Fornecedor_Compra)
                    .HasMaxLength(255)
                    .HasColumnName("Fornecedor Compra");

                entity.Property(e => e.Gama).HasMaxLength(255);

                entity.Property(e => e.Marca).HasMaxLength(255);

                entity.Property(e => e.Modelo_Comercial)
                    .HasMaxLength(255)
                    .HasColumnName("Modelo Comercial");

                entity.Property(e => e.Modelo_DPGC)
                    .HasMaxLength(255)
                    .HasColumnName("Modelo DPGC");

                entity.Property(e => e.Revenda).HasMaxLength(255);

                entity.Property(e => e.SKU).HasMaxLength(255);

                entity.Property(e => e.Serial).HasMaxLength(255);

                entity.Property(e => e.Valor).HasColumnType("money");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}